---
title: "fastGFPCA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fastGFPCA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(fastGFPCA)
library(tidyverse)
```


## Binary data

Simulate data that has periodic endpoints with 200 subjects and 100 timepoints

```{r}
# simulate data
bin_sim <- sim_gfpca(N = 100, J = 100, case = 1)

bin_mod <- fast_gfpca(bin_sim$df_gfpca, overlap = TRUE, binwidth = 5, npc = 4,
                      family = binomial)


bin_mod$family
bin_mod$time_step2
bin_mod$time_step4
# visualize results in some way 
```


Probit link

```{r}
binprob_mod <- fast_gfpca(bin_sim$df_gfpca, overlap = TRUE, binwidth = 10, npc = 5,
                          family = binomial(link = "probit"))

binprob_mod$family
```


## Count data

Outcome is count data simulated from a Poisson distribution.



```{r}
# simulate data
count_sim <- sim_gfpca(N = 200, J = 200, case = 1, family = "poisson")

count_mod <- fast_gfpca(count_sim$df_gfpca, overlap = TRUE, binwidth = 10, npc = 4,
                        family = "poisson")

count_mod$family
```


##  Interactive visualization

Using `refund.shiny` package

```{r, eval = FALSE}
library(refund.shiny)

bfpca_mod$Y <- bin_sim$df_gfpca
plot_shiny(bfpca_mod)

```

